CREATE TABLE IF NOT EXISTS schema_marker (
  version INTEGER PRIMARY KEY,
  applied_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
MERGE INTO schema_marker KEY(version) VALUES (1, CURRENT_TIMESTAMP);
